// Entry point for the build script in your package.json
import "@hotwired/turbo-rails"
import "./controllers"
// import "./test"
import "./bs_extra"
import "./ga4"
import * as bootstrap from "bootstrap"
import "trix"
import "@rails/actiontext"
import "chartkick/chart.js"